"""
api/video_coach.py
------------------
Analyses a climber's uploaded video and returns structured coaching advice.

Input: pose_frames rows for a single attempt (from pose_extractor output)
Output: list of Insight objects with category, severity, message, and drill

Insights are generated by comparing the climber's pose metrics against
grade-appropriate benchmarks (or generic best-practice thresholds if no
grade is given).

Categories
----------
  tension      — core / body tension (tension_score)
  arms         — straight-arm resting, over-gripping, reach efficiency
  hips         — hip position, hip spread, flagging
  footwork     — foot placement stability, weight on feet
  sequencing   — move efficiency, wasted movement
  breathing    — proxy: tension spikes between moves
"""

from __future__ import annotations

from statistics import mean, stdev
from typing import Optional


# ── Thresholds ────────────────────────────────────────────────────────────────
# (metric, [bad_lo, bad_hi], message, drill)
# bad_lo/hi: outside this range → flag. None = one-sided.

_TENSION_BENCHMARKS = {
    "V0–V3": (0.42, 0.58),
    "V4–V6": (0.50, 0.68),
    "V7–V9": (0.58, 0.76),
    "V10+":  (0.64, 0.82),
}

_GRADE_BAND = {
    "V0": "V0–V3", "V1": "V0–V3", "V2": "V0–V3", "V3": "V0–V3",
    "V4": "V4–V6", "V5": "V4–V6", "V6": "V4–V6",
    "V7": "V7–V9", "V8": "V7–V9", "V9": "V7–V9",
}

_DEFAULT_BAND = "V4–V6"


def _band(grade: Optional[str]) -> str:
    if not grade:
        return _DEFAULT_BAND
    g = grade.strip().upper()
    if g in _GRADE_BAND:
        return _GRADE_BAND[g]
    # V10+ catch-all
    try:
        n = int(g[1:])
        return "V10+" if n >= 10 else _DEFAULT_BAND
    except (ValueError, IndexError):
        return _DEFAULT_BAND


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_mean(vals):
    vals = [v for v in vals if v is not None]
    return mean(vals) if vals else None


def _safe_stdev(vals):
    vals = [v for v in vals if v is not None]
    return stdev(vals) if len(vals) >= 2 else None


def _pct(vals, threshold, above=True):
    """Fraction of frames above (or below) threshold."""
    vals = [v for v in vals if v is not None]
    if not vals:
        return 0.0
    if above:
        return sum(1 for v in vals if v >= threshold) / len(vals)
    return sum(1 for v in vals if v < threshold) / len(vals)


# ── Core analysis functions ───────────────────────────────────────────────────

def _tension_insight(frames: list[dict], grade: Optional[str]) -> Optional[dict]:
    vals = [f.get("tension_score") for f in frames]
    avg  = _safe_mean(vals)
    if avg is None:
        return None

    band   = _band(grade)
    lo, hi = _TENSION_BENCHMARKS.get(band, (0.50, 0.68))

    if avg < lo - 0.05:
        return {
            "category":  "tension",
            "severity":  "high",
            "score":     round(avg, 3),
            "benchmark": f"{lo:.2f}–{hi:.2f}",
            "message":   (
                f"Your average body tension ({avg:.0%}) is below the {band} benchmark "
                f"({lo:.0%}–{hi:.0%}). You're losing energy through a loose core — "
                "your hips are likely sagging away from the wall."
            ),
            "drills": [
                "Dead hangs with hollow-body hold (3×30s)",
                "Front levers negatives — lower as slowly as possible",
                "Plank-to-side-plank transitions on the wall (feet on, hands on)",
            ],
        }
    if avg > hi + 0.08:
        return {
            "category":  "tension",
            "severity":  "medium",
            "score":     round(avg, 3),
            "benchmark": f"{lo:.2f}–{hi:.2f}",
            "message":   (
                f"Your body tension ({avg:.0%}) is consistently very high. "
                "Over-tensing burns energy — try to relax on positive holds between crux sequences."
            ),
            "drills": [
                "Breathing reset drill: pause 2s on each jug and take one full breath",
                "Slow ascents at 2 grades below your limit — focus on fluid movement",
            ],
        }
    return None


def _straight_arm_insight(frames: list[dict]) -> Optional[dict]:
    pct_straight = _pct(
        [1 if (f.get("is_straight_arm_l") or f.get("is_straight_arm_r")) else 0
         for f in frames],
        0.5,
        above=True,
    )
    if pct_straight < 0.20:
        return {
            "category":  "arms",
            "severity":  "high",
            "score":     round(pct_straight, 3),
            "benchmark": "≥0.35",
            "message":   (
                f"You rested on bent arms in {(1-pct_straight):.0%} of frames. "
                "Bent-arm resting burns your biceps fast — train yourself to lock off "
                "on straight arms wherever possible."
            ),
            "drills": [
                "Straight-arm dead hang endurance: 3×45s at 70% BW",
                "Practice 'rest positions' drill: after every 3 moves, fully straighten both arms",
            ],
        }
    return None


def _reach_asymmetry_insight(frames: list[dict]) -> Optional[dict]:
    diffs = [
        abs((f.get("left_arm_reach_norm") or 0) - (f.get("right_arm_reach_norm") or 0))
        for f in frames
        if f.get("left_arm_reach_norm") is not None and f.get("right_arm_reach_norm") is not None
    ]
    avg_asym = _safe_mean(diffs)
    if avg_asym is None:
        return None
    if avg_asym > 0.18:
        return {
            "category":  "arms",
            "severity":  "medium",
            "score":     round(avg_asym, 3),
            "benchmark": "<0.12",
            "message":   (
                f"Left-right reach asymmetry is high ({avg_asym:.2f} avg). "
                "One arm is doing most of the work — this accelerates fatigue and "
                "limits dynamic moves requiring equal extension."
            ),
            "drills": [
                "Unilateral training: one-arm lock-offs on each side separately",
                "Traverse with deliberate equal reach — use a mirror or record yourself",
            ],
        }
    return None


def _hip_height_insight(frames: list[dict], grade: Optional[str]) -> Optional[dict]:
    vals = [f.get("com_height_norm") for f in frames]
    avg  = _safe_mean(vals)
    if avg is None:
        return None
    # Higher grades demand higher COM — hips close to wall
    target = 0.55 + (0.10 if (grade or "V4") >= "V7" else 0.0)
    if avg < target - 0.08:
        return {
            "category":  "hips",
            "severity":  "medium",
            "score":     round(avg, 3),
            "benchmark": f"≥{target:.2f}",
            "message":   (
                f"Your hips are consistently low ({avg:.0%} COM height). "
                "Drop your hips toward the wall — this transfers weight to your feet, "
                "reducing arm load and extending endurance."
            ),
            "drills": [
                "Hip-close wall stands: stand with feet on footholds, press hips into wall",
                "Flagging practice: deliberate single-leg flags on vertical terrain",
            ],
        }
    return None


def _wasted_movement_insight(frames: list[dict]) -> Optional[dict]:
    """High frame-to-frame COM variance → erratic movement."""
    vals = [f.get("com_height_norm") for f in frames]
    vals = [v for v in vals if v is not None]
    if len(vals) < 10:
        return None
    sd = stdev(vals)
    if sd > 0.14:
        return {
            "category":  "sequencing",
            "severity":  "medium",
            "score":     round(sd, 3),
            "benchmark": "<0.10",
            "message":   (
                f"Your center of mass moved erratically (std {sd:.2f}). "
                "Jerky, up-down movement wastes energy. Aim for a smooth, continuous arc "
                "— move through, not between, holds."
            ),
            "drills": [
                "Silent feet drill: place each foot without any sound",
                "Video yourself from the side — look for unnecessary up-down bounce",
                "Slow-motion ascent: every move takes 3+ seconds",
            ],
        }
    return None


def _hip_spread_insight(frames: list[dict]) -> Optional[dict]:
    vals = [f.get("hip_spread_deg") for f in frames]
    avg  = _safe_mean(vals)
    if avg is None:
        return None
    if avg < 18:
        return {
            "category":  "hips",
            "severity":  "low",
            "score":     round(avg, 1),
            "benchmark": "≥22°",
            "message":   (
                f"Hip spread averaged {avg:.0f}°. Keep your hips open — "
                "closed hips pull your body away from the wall and reduce reach."
            ),
            "drills": [
                "Hip mobility: frog stretches 3×60s",
                "Drop-knee practice: deliberate inside/outside edge transitions on a traverse",
            ],
        }
    return None


# ── Public API ────────────────────────────────────────────────────────────────

_SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2}


def analyse_attempt(frames: list[dict], grade: Optional[str] = None) -> dict:
    """
    Analyse pose frames for a single attempt and return coaching insights.

    Parameters
    ----------
    frames : list of pose_frames row dicts
    grade  : community grade string e.g. 'V6' (optional)

    Returns
    -------
    {
        "frame_count":  int,
        "grade":        str | None,
        "overall":      str,   # 'good' | 'needs_work' | 'critical'
        "insights":     list[Insight],
        "strengths":    list[str],
        "summary":      str,
    }
    """
    if not frames:
        return {
            "frame_count": 0,
            "grade":       grade,
            "overall":     "no_data",
            "insights":    [],
            "strengths":   [],
            "summary":     "No pose data available for this attempt.",
        }

    insights = []
    for fn in [
        lambda: _tension_insight(frames, grade),
        lambda: _straight_arm_insight(frames),
        lambda: _reach_asymmetry_insight(frames),
        lambda: _hip_height_insight(frames, grade),
        lambda: _wasted_movement_insight(frames),
        lambda: _hip_spread_insight(frames),
    ]:
        result = fn()
        if result:
            insights.append(result)

    insights.sort(key=lambda i: _SEVERITY_ORDER.get(i["severity"], 99))

    # Strengths: areas with no flagged insight
    all_categories = {"tension", "arms", "hips", "sequencing", "footwork"}
    flagged        = {i["category"] for i in insights}
    strength_map   = {
        "tension":    "Solid body tension throughout",
        "arms":       "Good straight-arm resting technique",
        "hips":       "Hips positioned well relative to the wall",
        "sequencing": "Smooth, efficient movement",
        "footwork":   "Stable footwork",
    }
    strengths = [strength_map[c] for c in all_categories - flagged if c in strength_map]

    high_count = sum(1 for i in insights if i["severity"] == "high")
    overall    = "critical" if high_count >= 2 else "needs_work" if insights else "good"

    summary_parts = []
    if not insights:
        summary_parts.append("No major technique issues detected — clean ascent.")
    else:
        top = insights[0]
        summary_parts.append(f"Primary focus: {top['category'].replace('_',' ').title()}. {top['message'][:80]}…")
    if strengths:
        summary_parts.append("Strong areas: " + ", ".join(strengths[:2]) + ".")

    return {
        "frame_count": len(frames),
        "grade":       grade,
        "overall":     overall,
        "insights":    insights,
        "strengths":   strengths,
        "summary":     " ".join(summary_parts),
    }
